import type { Language } from "./i18n";

const copy = {
  ko: {
    pages: {
      overview: "개요",
      projects: "프로젝트",
      agents: "에이전트",
      capabilities: "기능 관리",
      registry: "레지스트리",
      skills: "스킬",
      integrations: "연동",
      graph: "그래프",
    },
    pageDescriptions: {
      overview: "설치된 AI 환경과 현재 선택 범위를 한눈에 확인합니다.",
      projects: "로컬 프로젝트와 프로젝트별 세션·서브에이전트 내역을 확인합니다.",
      agents: "기본 세션과 그 아래 생성된 서브에이전트 계층을 확인합니다.",
      capabilities: "에이전트별 스킬과 연동 자산을 토큰 한도 안에서 채택하고 관리합니다.",
      registry: "프로젝트 에이전트의 중복과 유사성을 비교하고 글로벌 승격 후보를 검토합니다.",
      skills: "환경별 스킬을 프로그래밍 태그로 검색하고 비교합니다.",
      integrations: "플러그인, 훅, MCP 서버의 설치 및 활성 상태를 확인합니다.",
      graph: "환경에서 프로젝트, 세션, 서브에이전트로 이어지는 관계를 크게 봅니다.",
    },
    globalScope: "전체 환경",
    allProjects: "모든 프로젝트",
    environment: "환경",
    projectScope: "프로젝트 범위",
    currentScope: "현재 범위",
    detected: "감지됨",
    notDetected: "감지되지 않음",
    projects: "프로젝트",
    sessions: "세션",
    subagents: "서브에이전트",
    primarySessions: "기본 세션",
    recentActivity: "최근 활동",
    environmentCoverage: "환경 범위",
    openProject: "이 프로젝트 보기",
    viewAgents: "에이전트 보기",
    lastObserved: "최근 관찰",
    noProjectActivity: "선택 범위에서 프로젝트 활동을 찾지 못했습니다.",
    noAgentActivity: "선택 범위에서 에이전트 세션을 찾지 못했습니다.",
    projectHistory: "프로젝트 내역",
    agentHierarchy: "에이전트 계층",
    parentSession: "부모 세션",
    standalone: "독립 세션",
    role: "역할",
    source: "출처",
    assets: "자산",
    installedCapabilities: "설치 기능",
    projectAssetsNotice: "스킬과 연동 자산은 환경 전역 설정이며 프로젝트 필터와 별도로 표시됩니다.",
    searchProjects: "프로젝트 검색",
    searchAgents: "에이전트·역할 검색",
    searchSkills: "스킬·태그 검색",
    searchIntegrations: "플러그인·훅·MCP 검색",
    environmentGraph: "환경 관계도",
    graphHint: "노드를 선택하면 같은 프로젝트의 세션 계층을 강조합니다.",
    liveMetadataOnly: "대화 본문 없이 로컬 메타데이터만 읽습니다.",
    projectCount: "프로젝트 수",
    sessionCount: "세션 수",
    subagentCount: "서브에이전트 수",
    selectedProject: "선택된 프로젝트",
    clearProject: "프로젝트 범위 해제",
    previous: "이전",
    next: "다음",
    page: "페이지",
    of: "/",
  },
  en: {
    pages: {
      overview: "Overview",
      projects: "Projects",
      agents: "Agents",
      capabilities: "Capabilities",
      registry: "Registry",
      skills: "Skills",
      integrations: "Integrations",
      graph: "Graph",
    },
    pageDescriptions: {
      overview: "See installed AI environments and the current scope at a glance.",
      projects: "Inspect local projects and their sessions and subagents.",
      agents: "See primary sessions and the subagent hierarchy created beneath them.",
      capabilities: "Adopt and manage agent skills and integrations behind hard token ceilings.",
      registry: "Compare duplicate project agents and review candidates for global promotion.",
      skills: "Search and compare skills by environment and programming tag.",
      integrations: "Inspect installed and enabled plugins, hooks, and MCP servers.",
      graph: "Use the full canvas for environment, project, session, and subagent relationships.",
    },
    globalScope: "All environments",
    allProjects: "All projects",
    environment: "Environment",
    projectScope: "Project scope",
    currentScope: "Current scope",
    detected: "Detected",
    notDetected: "Not detected",
    projects: "Projects",
    sessions: "Sessions",
    subagents: "Subagents",
    primarySessions: "Primary sessions",
    recentActivity: "Recent activity",
    environmentCoverage: "Environment coverage",
    openProject: "View this project",
    viewAgents: "View agents",
    lastObserved: "Last observed",
    noProjectActivity: "No project activity was found in the selected scope.",
    noAgentActivity: "No agent sessions were found in the selected scope.",
    projectHistory: "Project history",
    agentHierarchy: "Agent hierarchy",
    parentSession: "Parent session",
    standalone: "Standalone session",
    role: "Role",
    source: "Source",
    assets: "Assets",
    installedCapabilities: "Installed capabilities",
    projectAssetsNotice: "Skills and integrations are environment-wide settings and are shown independently of project scope.",
    searchProjects: "Search projects",
    searchAgents: "Search agents or roles",
    searchSkills: "Search skills or tags",
    searchIntegrations: "Search plugins, hooks, or MCP",
    environmentGraph: "Environment graph",
    graphHint: "Select a node to emphasize sessions in the same project.",
    liveMetadataOnly: "Reads local metadata only, never conversation content.",
    projectCount: "Project count",
    sessionCount: "Session count",
    subagentCount: "Subagent count",
    selectedProject: "Selected project",
    clearProject: "Clear project scope",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
  },
} as const;

export type EnvironmentCopy = (typeof copy)[Language];

export function ec(language: Language): EnvironmentCopy {
  return copy[language];
}
