import type { Language } from "./i18n";

const copy = {
  ko: {
    eyebrow: "에이전트 정체성 계층",
    title: "Agent Registry",
    description: "프로젝트마다 반복되는 에이전트를 비교하고 글로벌 승격 후보를 검토합니다.",
    globalAgents: "글로벌 에이전트",
    projectDefinitions: "프로젝트 서브에이전트",
    promotionCandidates: "승격 후보",
    exactDuplicates: "완전 중복",
    promotionQueue: "글로벌 승격 후보",
    queueDescription: "두 개 이상의 프로젝트에서 반복된 정의만 표시합니다.",
    all: "전체 후보",
    exact: "완전 중복",
    review: "검토 필요",
    noCandidates: "현재 범위에서 글로벌 승격 후보를 찾지 못했습니다.",
    projects: "프로젝트",
    usages: "실행",
    similarity: "유사도",
    reviewPromotion: "승격 검토",
    preview: "승격 미리보기",
    previewDescription: "프로젝트 정의를 하나의 글로벌 기준으로 연결하기 전 차이를 확인합니다.",
    globalTarget: "제안된 글로벌 에이전트",
    sourceDefinitions: "프로젝트별 원본",
    evidence: "유사도 근거",
    matched: "공통",
    different: "차이",
    preparePlan: "승격 계획 미리보기",
    planPrepared: "승격 계획을 준비했습니다. 아직 어떤 파일도 변경하지 않았습니다.",
    previewOnly: "읽기 전용 미리보기입니다. 승격은 영향 범위와 권한을 다시 확인한 뒤 별도 승인으로 실행합니다.",
    selectCandidate: "왼쪽 후보를 선택하면 병합 근거와 프로젝트별 차이를 확인할 수 있습니다.",
    globalInventory: "현재 글로벌 정의",
    noGlobalAgents: "현재 범위에서 명시적인 글로벌 에이전트를 찾지 못했습니다.",
    crossEnvironment: "환경 간 호환성 검토 필요",
    exactConfidence: "동일 정의",
    highConfidence: "높은 확신",
    reviewConfidence: "수동 검토",
    features: {
      name: "이름",
      role: "역할",
      tags: "태그",
      capabilities: "기능",
      skills: "스킬",
      mcpServers: "MCP",
      permissions: "권한",
    },
  },
  en: {
    eyebrow: "Agent identity layer",
    title: "Agent Registry",
    description: "Compare recurring project agents and review candidates for global promotion.",
    globalAgents: "Global agents",
    projectDefinitions: "Project subagents",
    promotionCandidates: "Promotion candidates",
    exactDuplicates: "Exact duplicates",
    promotionQueue: "Global promotion candidates",
    queueDescription: "Only definitions repeated across two or more projects are shown.",
    all: "All candidates",
    exact: "Exact duplicates",
    review: "Needs review",
    noCandidates: "No global promotion candidates were found in the current scope.",
    projects: "Projects",
    usages: "Runs",
    similarity: "Similarity",
    reviewPromotion: "Review promotion",
    preview: "Promotion preview",
    previewDescription: "Inspect differences before connecting project definitions to one global source.",
    globalTarget: "Proposed global agent",
    sourceDefinitions: "Project sources",
    evidence: "Similarity evidence",
    matched: "Shared",
    different: "Different",
    preparePlan: "Preview promotion plan",
    planPrepared: "The promotion plan is ready. No files have been changed.",
    previewOnly: "This is a read-only preview. Promotion requires a separate approval after impact and permissions are reviewed.",
    selectCandidate: "Select a candidate on the left to inspect merge evidence and project differences.",
    globalInventory: "Current global definitions",
    noGlobalAgents: "No explicit global agents were found in the current scope.",
    crossEnvironment: "Cross-environment compatibility review required",
    exactConfidence: "Exact definition",
    highConfidence: "High confidence",
    reviewConfidence: "Manual review",
    features: {
      name: "Name",
      role: "Role",
      tags: "Tags",
      capabilities: "Capabilities",
      skills: "Skills",
      mcpServers: "MCP",
      permissions: "Permissions",
    },
  },
} as const;

export function rc(language: Language) {
  return copy[language];
}
